language: java
sudo: false
jdk:
  - oraclejdk7
  - openjdk6
before_install:
  - pip install awscli
script: cd ${TRAVIS_BUILD_DIR}/demo && mvn clean package
after_success:
  - aws s3 cp ${TRAVIS_BUILD_DIR}/demo/target/ticket-monster.war s3://ansible-demo-build-artifacts/ticket-monster/${TRAVIS_COMMIT}/ticket-monster.war
  - ${TRAVIS_BUILD_DIR}/deploy-app.sh
